seL4/camkes-tool

- camkes/runner/__main__.py
Use of PyYAML's yaml.load function without specifying the Loader=... parameter, has been deprecated.
> disable YAML loading warning

- camkes/runner/Context.py
- camkes/runner/__main__.py
Recent changes to capdl mean that `get_object_sizes` is invoked if the `levels` is called. Prevent this.
> Avoid render

- camkes/templates/macros.py
Previously `next_page_multiple` calculated the smallest page multiple that can fit a dataport by multiplying by 2 everytime from a base of 4096. This was because of the dataport size `static_asserts` were checking if the size was aligned to a power of 2. Now that this isn't the case anymore (commit 6c19155), we 'fix' `next_page_multiple` so that it adds increments of 4096. This also helps in saving memory by only allocating what we need.
> Fix next_page_multiple in macros.py

- camkes/templates/seL4HardwareMMIO.template.c
I'm getting a compiler warning
`error: ‘_camkes_frame_caps_2567’ defined but not used [-Werror=unused-const-variable=]` because nobody seems to use the symbol. This patch declares it as unused to prevent the warning, but still keeps it. I got told that this symbols was used in a `xxx_flush_cache()` function once, but all this has been refactored out into libsel4camkes which obtains the information for the cap from the `dataport_frame_t xxx_0` definition now. So the actual plan seems to be to remove it completely. I would do this, but I'm not a CAmkES template expert and thus not sure what else should be remove there. Instead, I go with the minimal invasive change now and just declare it as unused.
> template: mark symbol as unused to avoid compiler warning

- camkes/templates/seL4HardwareInterrupt.template.c
Define a compatible IRQ Ack function to be passed to irq_callback_fn_t
@ssrg-bamboo `test`
> seL4HardwareInterrupt: Fix compilation warning

- camkes/templates/seL4HardwareInterrupt.template.c
- libsel4camkes/include/camkes/tls.h
Include the generated configuration header file to avoid a warning about the undefined TLS model.
> config: include configuration header file

- camkes/templates/tests/jinja_lint.py
- tools/jinja_lint.py
These changes make the Jinja linter useful on any arbitrary Jinja template. Not sure if you want to take this as-is, because it introduces a dependency on Python ≥ 3.6
> generalise Jinja linter to support non-CAmkES use cases

- libsel4camkes/src/sel4_arch/ia32/gdb_server/serial.c
I think the FIFO must be checked for every char that is sent, otherwise the char could be lost. Issue might not happen in real life by luck, because things are never pushed to the limits.
> output: update and check FIFO for every char

- camkes/templates/camkes-gen.cmake
The change of https://github.com/seL4/camkes-tool/commit/80ce2676941d0ebece38d66f803f7fa0051fa1a7 does not work for me, the build always fails with 
ninja: error: 'main/include/camkes.h', 
needed by '<my_system>/CMakeFiles/main.instance.bin.dir/main/camkes.c.obj', 
missing and no known rule to make it
where `<my_system>` is a custom sub folder I'm using to place my CAMkES system in to avoid naming conflicts.
This patch fixed the build for me. But I don't fully understand the what the original commit tried to do and by fix here might contradict this.
> camkes: Fix build breaker

- camkes.cmake
The define CAMKES_TOOL_PROCESSING can be used in shared C header file to detect if the CAmkES tool is running or the C compiler. This allows excluding things from the CAmkES tool that are either unsupported or not relevant.
Signed-off-by: Axel Heider <axelheider@gmx.de>
> tools: define CAMKES_TOOL_PROCESSING when running the C preprocessor

- camkes/runner/Context.py
seL4SignalRecv does not exist in the normal kernel, this commit splits
the two calls so that the compilable code can be generated.
> runner: Fix generate_seL4SignalRecv

- camkes/parser/stage0.py
Since we use more and more preprocessor magic on the CAmkES files, I found it handy if the resulting files are saved, so they are available to look at them when running into strange errors that are just typos in the end.
Preceding commit addresses all the style issues. Might make sense to merge this in any case.
> parser: save preprocessed camkes files

- camkes/templates/linker.lds
The correct functioning of the thread-local-storage implementation
requires the linker to correctly initialize _tbss_end and _tdata_start
variables to sizes that reflect the true size of the static TLS region.
In order for this to work, these variables can only be declared in the
final linking stage of the executable. In the case of Rumprun camkes
components, there is an additional linker step where the rumprun
userlevel binaries are linked with the rumprun base (which is what the
camkes templated linker script refers to.). So this case must be handled
similarly to grouped components, where the .tdata_* and .tbss_* linker
symbol declarations are suppressed until the final link step.
Signed-off-by: Kent McLeod <kent.mcleod@protonmail.com>
Fixes seL4/camkes-manifest#5
> camkes,rumprun: Fix TLS management implementation

- camkes/parser/camkes.g
- camkes/templates/component.template.h
- camkes/templates/macros.py
- docs/index.md
CAmkES was missing a way of creating a static attributes (evaluated at
the compile time).
Thanks to this, we can e.g. have arrays of a size that are component's
instance specific:
```
// foo.camkes
component Foo {
static_attribute N = 1;
// foo.c
static int data[N];
}
// main.camkes
assembly {
composition {
component   Foo      foo;
component   Foo      bar;
}
configuration {
foo.N = 10;
bar.N = 20;
}
}
```
> Add static attribute

- camkes/templates/camkes-gen.cmake
I could not find where this is use actually, so I assume it's a left-over artifact that can be removed
> cmake: remove unused variable

- camkes/templates/camkes-gen.cmake
- camkes/templates/component.template.h
Remove generated shell script camkes.h.cmd and camkes.h.in. Use a
lightweight camkes.h instead that includes a component-specific
generated header camkes-component-<component>.h and the interface
template headers.
> camkes: remove CMAKE_INTERFACE_INCLUDES

- libsel4camkes/src/sys_uname.c
make it generic, so there is no immediate need to modify this file when adding a new platform.
> libsel4camkes: make uname generic, add RISC-V

- camkes.cmake
- camkes/parser/stage0.py
1.  Simplify CMake files
2. Set the current working directory explicitly to be the build output folder. This was missing in the past and thus the fiels were not necessarily created in the folder where the build output is, but form where the build was started. Since most build script seem to do `cd <build-out-dir>; cmake ....` this was not noticed. But if `cmake -S <src> -B <build-output> ...` is used, the files suddenly pop up in a subfolder of the folder where the build is invoked and not in `<build-output>`.
3. Let the CAmkES parser create the output files in the current working directory and don't create a subfolder - this was needed due to the "bug" that (2) "fixes" now. One day the parser could get a parameter that allows defining where the output goes. Until then, simply use the …
> camkes-tool: create file in current working directory

- camkes/templates/arch-definitions.thy
The variable `type` ironically does not have the correct type for the
check to be useful. Use `param.type` instead.
> Fix handling of array parameters

- camkes/templates/arch-definitions.thy
We are building a moderately sized (<=8 components, <=20 instances, ~30 connections) assembly and have run into problems with the proofs in the generated arch spec. The simpset and goal are too large for the simplifier to efficiently solve the given goals.
These commmits improve the proving times by using refined proof ideas. The speedup mainly comes from
* using the newly defined `wf_XXX` named theorem sets to selectively unfold specific classes of camkes objects only
* efficiently dealing with proving `ex_one P xs` by using a custom method which traverses the list head-to-tail, eagerly forcing evaluation of the `if`-branch. I suspect that in the previous case `simp` starts exploring the exponential term space, which is too slow.
This commit also depends on a slight adjustment in `l4v`, …
> Speed up proofs in generated arch spec

- camkes.cmake
The extra_dependencies argument of execute_process_with_stale_check
takes a CMake list of files.  This is of the form "a;b;c;d;e". Without
the semicolon separator, CMake would consider a space separated pair of
files as being a single list element.
Signed-off-by: Kent McLeod <kent@kry10.com>
> cmake: Fix cmake argument marshalling bug

- camkes/templates/camkes-gen.cmake
Remove the status cmake messages that are printing the value of some
internal camkes cmake variables that were previously used for debugging
purposes and not usually informative for a typical build.
Signed-off-by: Kent McLeod <kent@kry10.com>
> camkes-gen.cmake: Remove debug status messages

- .github/workflows/unit.yml
Still has to pointed at `camkes-unit@master` when  seL4/ci-actions#105 is merged.
> Add GitHub action for CAmkES Unit tests

- camkes/templates/rpc-connector-common-from.c
The  latest version of cppcheck complain about some uninitialized variables being used in generated code.
16:08:20  timeServer_rpc_seL4RPCCall_1.c:238:24: error: Uninitialized variable: *return_ptr [uninitvar]
16:08:20                  return * return_ptr;
16:08:20                         ^
16:08:20  timeServer_rpc_seL4RPCCall_1.c:229:32: note: Address of variable taken here.
16:08:20        OS_Error_t *return_ptr = &return_val;
16:08:20                                 ^
16:08:20  timeServer_rpc_seL4RPCCall_1.c:238:24: note: Uninitialized variable: *return_ptr
16:08:20                  return * return_ptr;
16:08:20                         ^
16:08:20  timeServer_rpc_seL4RPCCall_1.c:370:24: error: Uninitialized variable: *return_ptr [uninitvar]
16:08:20                  return * return_ptr; …
> camkes: add default value for return value in rpc connector from

- camkes.cmake
- camkes/templates/camkes-gen.cmake
Allows C++ source files to be used in the creation of camkes components. Extends the DeclareCAmkESComponent function with the CXX_FLAGS argument.
> camkes: Allow c++ source files to be used for the creation camkes components

- libsel4camkes/src/sys_uname.c
use CONFIG_PLAT for all architectures in `camkes_sys_uname()`
> libsel4camkes: use CONFIG_PLAT for all architectures

- .github/workflows/test.yml
These are the app tests from Bamboo, including simulation and hardware builds. Hardware runs not yet includes (blocked on machine queue).
See seL4/ci-actions#129 for the actual test code.
> github: add GitHub action for CAmkES test

- camkes/templates/camkes-gen.cmake
When linking multiple components together to create a "grouped"
component we run some objcopy commands to remove unsupported and unused
sections such as the .eh_frame.  Some toolchains don't allow this and
cause objcopy to error but this shouldn't cause the build step to fail.
The build rule was already trying to catch the error according to its
preceding comment, but now it does this correctly.
Signed-off-by: Kent McLeod <kent@kry10.com>
> camkes-gen.cmake: best-effort build step can error

- .github/workflows/camkes-deploy.yml
- .github/workflows/test.yml
This workflow runs simulation + HW builds + HW tests on push to master or on repository dispatch messages, and deploys to camkes-manifest when all of these pass.
The corresponding CI action PR is at seL4/ci-actions#152
> CAmkES hardware tests + deployment

- camkes/parser/camkes.g
The lexxer showed syntax errors when working with attribute references
using '<-'. The regular expression for angle_string is being checked by
the lexxer when encountering the '<' first.
So if the file to be parsed contains a '>' following the attribute
reference, the lexxer will tokenize everything from '<-' to this '>',
leading to a syntax error.
Examples for this behaviour would be an import statement with angled
brackes or an export statement containing '->'.
The proposed fix adds further characters to be excluded in the regular
expression, to avoid the angle_string rule to be active in such cases.
Signed-off-by: Thomas Wittal <thomas.wittal@hensoldt-cyber.de>
>  parser: fix attribute_reference regex 

- CHANGES
- camkes/templates/arch_helpers.py
- camkes/templates/dtb-query-common.template.c
- camkes/templates/macros.py
- camkes/templates/seL4DTBHardware-to.template.c
Seems on ARM this was always used with device trees that have 3 values per interrupt or extended interrupts that have just one interrupt. Fix the handling for extended interrupts to allow more than one. Add support for device trees (e.g. RISC-V HiFive) that use only one value per interrupt. This is a hack that add some smart guessing to accept them also. More documentation is also added about the problems. The long term fix should be properly parsing the device tree, as it is done in the kernel already.
> RISC-V: Support DTBs with one interrupt value per cell

- camkes/runner/__main__.py
Library no longer used in camkes
> camkes: Remove unused python library

- cdl-refine-tests/run_tests
- docs/index.md
- libsel4camkes/src/sys_uname.c
This platform has been removed from seL4 due to ending support. The
sabre platform should be substitutable for camkes examples.
See: seL4/seL4#578
> Remove references to kzm platform

- camkes/ast/base.py
- camkes/ast/liftedast.py
- camkes/internal/frozendict.py
- camkes/internal/hash.py
1. collections.Mapping, collections.Hashable, collections.Iterable, etc are deprecated in Python3.3, removed in Python3.10. Ref to: [collections.abc](https://docs.python.org/3/library/collections.abc.html)
2. Fix style for Python3 style check
Signed-off-by: Homalozoa <xuhaiwang@xiaomi.com>
> trivial: Fix Python3 collections

- camkes/runner/Context.py
When generating a set of frames to cover a region, use as many digits
as necessary so that the capdl tool, when it sorts alphabetically,
will still leave frames that are meant to be contiguous contiguous.
Without this change, we had
vm0_dma_1_obj
vm0_dma_10_obj
vm0_dma_11_obj
...
vm0_dma_19_obj
vm0_dma_2_obj
vm0_dma_20_obj
etc; with the change we see
vm0_dma_01_obj
vm0_dma_02_obj
...
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
> Name frames in a region for easy sorting

- camkes/runner/Context.py
- tools/check_deps.py
- tools/python-deps/setup.py
The orderedset PyPi package no longer works with Python 3.10,
and has not been updated for years.
Replace it with the functionally equivalent (but maintained) ordered-set
package.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
> Replace orderedset with ordered_set

- tools/python-deps/setup.py
The `jinja2` API changes after version 3.0, which is relevant for the use of `contextfilter` etc in the seL4 tutorials.
https://github.com/seL4/sel4-tutorials/pull/91 fixes the issue for newer versions, but this means we do need a minimum jinja2 version now.
> set minimum jinja2 version

- camkes/templates/component.common.c
This region is used for mmap and brk allocations. The implementations
assume that it is 4k aligned. If the alignment isn't obeyed then memory
errors are possible.
Signed-off-by: Kent McLeod <kent@kry10.com>
> component.common: Align morecore region to 0x1000

- components/plat/pc99/plat/CMakeLists.txt
- components/plat/pc99/plat/components/serial_com1/Serial.camkes
- components/plat/pc99/plat/components/serial_com2/Serial.camkes
- components/plat/pc99/plat/components/serial_com3/Serial.camkes
- components/plat/pc99/plat/components/serial_com4/Serial.camkes
- components/plat/pc99/plat/serial.camkes
The previous Serial component assumes that only serial port com1
is used. Since users are able to config serial ports, the Serial
component should also be able to include a different definition
based on the libplatsupport CMake configuration values.
Signed-off-by: Jingyao Zhou <jingyao.zhou@unsw.edu.au>
> serial: add config options for different ports

- libsel4camkes/src/irq.c
The guards for the equality checking in
check_irq_into_is_equal were the wrong way around.
Also simplify the logic.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
> Fix IOAPIC vs MSI check in irq.c

- camkes.cmake
The CMake code seems to support passing a DTB also, but it's not exposed for the function parameter parsing. Is there are reason for it (besides nobody using this) or is this just missing?
> CMake: add missing parameter DTB_FILE_PATH

- libsel4camkes/include/camkes/virtqueue.h
- libsel4camkes/src/virtqueue.c
Exposing this function allows us to play with the underlying channels and their buffers.
Test with: https://github.com/seL4/seL4_projects_libs/pull/88
> libsel4camkes: Expose get_virtqueue_channel

- libsel4camkes/src/irq.c
Usually, it's quite uncommon to compare explicitly to 'true' or 'false'. Especially 'true' can be dangerous as any value that is not 'false' (0) is considered to be "true". Since c99 there is a bool type, so this should be ok, but it still feels odd using this explicit comparison, and it not done anywhere else either.
> don't compare explicitly to 'true' or 'false'

- camkes/templates/camkes-gen.cmake
That `endmacro()` takes the name as parameter is legacy already, but the parameters are not supposed to be listed there. This is the minimal change. Actually I'd prefer to change it to `endmacro()` everywhere in the file, as this also removes some redundancy then.
> cmake: fix endmacro()

- camkes/templates/component.template.h
If there are mismatches in the device tree, it's helpful to know which node cause the problem, and what exactly the problem was. Without these messages, it was quite painful to figure out what exactly failed here.
> camkes: improve error messages

- camkes/templates/component.common.c
- camkes/templates/component.template.h
These commits make the following general improvements: 
- add a camkes function to allow a component to get the affinity that was set for it in the camkes config
- add a build time error checking for the affinity and num_vcpus attributes to avoid needing to wait for runtime errors to occur
- allow a components fault handler thread to always be on the same core as it's control thread when the affinity attribute is set
> General Multicore Improvements

- camkes/parser/fdtQueryEngine.py
When using dtb queries on a type that has multiple instances, when the second or additional instances are evaluated, their settings have bad values: `gpio_mux_server1.gpio.dtb = dtb({})` instead of the expected: `gpio_mux_server1.gpio.dtb = dtb({"path" : "/gpio@2200000"})`.  This is due to a parser bug that mutates the internal dictionary object instead of mutating a copy.
Switching to a deep copy avoids mutating the AST object.
```
component GPIOMUXServer {
emits FDT dummy_source;
consumes FDT gpio;
consumes FDT mux;
composition {
connection seL4DTBHardware gpio_conn(from dummy_source, to gpio);
connection seL4DTBHardware mux_conn(from dummy_source, to mux);
}
configuration {
gpio.dtb = dtb({"path" : "/gpio@2200000"});
mux.dtb = dtb({"path" : "/pinmux@2430000"});
}
}
assembly { …
```
> parser,fdtQueryEngine: Fix parser bug with queries

- camkes/templates/component.common.c
Add a new capability which certain threads can invoke so seL4 can make SMC calls on ARM platforms in EL2 (virtualized mode) on the thread’s behalf.
See https://sel4.atlassian.net/browse/RFC-9
> SMC Capability

- .github/workflows/camkes-deploy.yml
The old node12 actions are deprecated and will stop working.
> github: bump GitHub action versions

- camkes/templates/component.simple.c
Fix this #139. Using macro to select the build-in function in different type size.
For more background and discussion see also https://github.com/seL4/util_libs/pull/176
> templates: fix mismatched type size in simple

- libsel4camkes/README.md
- libsel4camkes/docs/allocator.md
- libsel4camkes/docs/dataport.md
- libsel4camkes/docs/dma.md
- libsel4camkes/docs/error.md
- libsel4camkes/docs/fault.md
- libsel4camkes/docs/init.md
- libsel4camkes/docs/marshall_macros.md
- libsel4camkes/docs/msgqueue.md
- libsel4camkes/docs/pid.md
- libsel4camkes/docs/ps_io_ops_t.md
- libsel4camkes/docs/syscalls.md
- libsel4camkes/docs/timing.md
- libsel4camkes/docs/tls.md
- libsel4camkes/docs/virtqueue.md
- libsel4camkes/docs/vma.md
This commit adds documentation written in markdown that explains each part of the libsel4camkes library in more depth.
This appears to be draft documentation started by @kent-mcleod as part of developing the seL4 Device Driver Framework. It looks to be incomplete.
This might assume the API changes from https://github.com/seL4/camkes-tool/pull/84
> libsel4camkes: Add markdown documentation

- camkes/runner/Context.py
- Fix the calculation of leading zeros. Using "`int(log10(cnt + 1)) + 1`" is broken, it evaluates to 2 for cnt=9, and thus results in the strings "`00`"-"`08`". Using "`1 if (n <= 1) else (1 + int(log10(n - 1)))`" seems overly complicated here, so a naive and readable way is used.
- switch to f-strings for better readability
> python: sanitize number formatting

- .github/workflows/push.yml
- tools/check_deps.py
- tools/python-deps/setup.py
- commit 4f7bca1931 replaced orderedset by the maintained ordered-set, but did no yet remove the dependency. Since on more recent python version the dependency install now fails, we are removing it completely.
- make python 3 requirement explicit
To be released on PyPi simultaneously with the upcoming CAmkES release.
Closes #124
> camkes-deps: fully remove orderedset; bump version

- VERSION
This reverts commit 0f02fe2d18393df04eb7017b6603aca7b474bb3a to get CI to trigger on the release commit state.
> recreate camkes-3.11.0 release state

- .github/workflows/camkes-deploy.yml
Python 3.12 in Ubuntu 24.04 has incompatible packages.
> github: pin Ubuntu 22.04 for deployment step

- .github/workflows/pr.yml
- .github/workflows/push.yml
- .linkcheck-ignore.yml
Use GitHub workflow_call feature to reduce workflow duplication.
The `linkcheck-ignore.yml` feature doesn't really exist yet, but I'm planning to add it this weekend.
> github: use central CI workflows

- docs/index.md
Fix internal links in the manual.
- anchors of headings with `.` are rendered without the `.`
- the template environment had been renamed to template context
> manual: fix links
